# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Echoes of Nature
author: Hong Kong Listening Project
logo: logo.png
only_build_toc_files: true

parse:
  # https://jupyterbook.org/content/content-blocks.html?highlight=myst%20substitution#define-substitutions-for-your-whole-book
  # https://jupyterbook.org/content/content-blocks.html#using-substitutions-in-links
  myst_substitutions:
    hackweek: "HKLP"
    dates: "July 2025 to December 2027"
    github_org_url: "https://yuenwaho.github.io/HKListeningProject"
    book_repo: "jupyterbook-template"
    website_url: "https://book-template.hackweek.io"
    jupyterhub_url: "https://INSERT_JUPYTERHUB_URL"
    slack_workspace_url: "https://INSERT_SLACK_URL"
    contact_email: "hoyuenwa@cetacea-institute.org"
    dataset: "INSERT_DATA_SET_NAME"
    anon_reporting_url: "https://INSERT_FORM_LINK"
    project_spreadsheet_url: "https://INSERT_GOOGLE_SHEET"
  myst_enable_extensions:
    # Defaults
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    # Extras
    - html_image

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  # NOTE: 'cache' to use jupyter-cache, or 'force' to run all
  execute_notebooks: "force"
  exclude_patterns:
    - "**/geospatial-advanced.ipynb"
  allow_errors: true  # Changed to true to see full error output
  # Per-cell notebook execution limit (seconds)
  timeout: 600  # Increased timeout to 10 minutes

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: "https://mybinder.org"

# Information about where the book exists on the web
repository:
  url: https://github.com/uwhackweek/jupyterbook-template # Online location of your book
  path_to_book: book # Optional path to your book, relative to the repository root
  branch: main # Which branch of the repository should be used when creating links (optional)

# Bibliography
bibtex_bibfiles:
  - references.bib

# Notebook configuration
myst_nb:
  merge_streams: true
  output_stderr: show
  render_text_lexer: myst-ansi
  render_error_lexer: ipythontb
  render_image_options: {}
  render_figure_options: {}
  render_markdown_format: commonmark
  output_folder: build
  append_css: true

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  # google_analytics_id: G-XXXXXXXXX
